### PR TITLE
Besley update

### PR DESCRIPTION
**Pull request by emmamarichal**
Hello @EwonRael 

I'm Emma, I'm working on the onboarding of your font, as part of its update. 
The exported fonts in your repo didn't pass the fontbakery tests, so I had to convert them to glyphs file to fix the bugs. I exported new ufo files in the 21.07.22_Ufos folder. Can you tell me if you can read them well with fontforge? 

In any case, I didn't touch the design, except I added to the font some numbers that were missing, like the 6 and 8 in the .osf and .tosf, and also the Acaron and acaron. The font is ready to be onboarded 💪

If you have any question, don't hesitate!
Cheers!

### CODE REVIEW

**Comment by emmamarichal** [comment]
Hi @EwonRael ! Have you seen this PR? You can take a look to this, and if it's ok for you, you can merge it so I can onboard it then :)

**Comment by ctrlcctrlv** [comment]
@emmamarichal Hello, I also work a lot on this font, and have done a lot of work in related software (alerque/sfdnormalize#11; [ctrlcctrlv/sfdutf7.py](https://github.com/ctrlcctrlv/sfdutf7.py); <https://github.com/fontforge/fontforge/pull/5078>—literally all of these patches were created just in my trying to get the font to build again) to get to the rebuild I just completed, so was surprised to see your patch.

Well anyway, this is going to cause a diversion. FontForge cannot read the proprietary Glyphs format and can only at pains merge changes from its UFO exports.

* I believe my patch already does what you did in https://github.com/indestructible-type/Besley/pull/23/commits/f498dd4e11d5bd682f25593c82ec51ff53ab7ec6 as I (too?) noticed a collision. 
* I can rename `woff2` to `webfonts` to match your https://github.com/indestructible-type/Besley/pull/23/commits/173221e0bb2de6a6da04fc942372eb49a3659873
* I don't know what is wrong with ogonek alignment but can look at it and try to fix it.

In general I doubt @indestructible-type will want to merge several 2MB files that are not dissimilar to binary blobs, in that while they can be built with free software they can't be _edited_ with free software, at least well, until MFEK gets farther along that is ;-) (MFEK has UFO as its native format, not SFD.)

**Comment by davelab6** [comment]
@ctrlcctrlv can you take the improvements to metadata and added glyphs, into your fork, so that the TTF output of your fork matches @emmamarichal 's TTFs here, and then this can be closed and yours merged and then this repo shipped in gf?

**Comment by ctrlcctrlv** [comment]
That's a good idea of how to proceed—yes I can. I already see what she means about the ogonek.

By the way—there's also [MFEK/MFEK-Serif.otf](https://github.com/MFEK/MFEK-Serif.otf), but I'm not really advertising that repository yet because I haven't yet worked out how I want to do the "branding switch". It should not be that hard if this PR is merged, just a switch of the familyname (and a find/replace in the stylemapfamilyname).

**Comment by ctrlcctrlv** [comment]
(By the way:

I don't really plan to commission a lot of fonts, I decided though that Besley was a good idea to commission changes to because it's a really big challenge, to get the UFO output's (and MFEK's interaction with them) to the level that you no longer need to build from FontForge…

None of my fonts are this technically complex (three variable axes, lots of technical debt) so it's a good challenge for the project, most of my fonts I already have in tons of formats and can easily make a workflow for any change regardless of how I do it.)

**Comment by emmamarichal** [comment]
Can I close this PR since the font is still in progress?

**Comment by ctrlcctrlv** [comment]
Depends on who you ask what progress looks like :-)

**Comment by emmamarichal** [comment]
@ctrlcctrlv Ah, I see you made new PRs yesterday, so I'll close this one as it doesn't seem to be useful anymore! :)

**Pull request closed without merging**
